spring.application.name=vorstu
spring.datasource.url=jdbc:postgresql://localhost:5433/vorstu_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=KTNhpyOAGHM7etBlS7FbvTKgeuf5YiX7GaviFlRGiif
jwt.access-expiration-minutes=60
jwt.refresh-expiration-days=1